export const componentCatalog = Object.freeze([
  { slug: 'button', title: 'Button', description: 'Action hierarchy, sizes, icons, loading, toggles, and disabled states.' },
  { slug: 'link', title: 'Link', description: 'Inline, subtle, standalone, inverse, current, and disabled navigation.' },
  { slug: 'badge-chip', title: 'Badge and Chip', description: 'Read-only status and interactive, accessible filter selection.' },
  { slug: 'field', title: 'Field', description: 'Labels, guidance, errors, required values, and responsive composition.' },
  { slug: 'input-textarea', title: 'Input and Textarea', description: 'Text entry, sizes, adornments, validation, and character limits.' },
  { slug: 'select', title: 'Select', description: 'Designed listbox selection with native sizes, groups, validation, and fallback.' },
  { slug: 'checkbox-radio', title: 'Checkbox and Radio', description: 'Independent and exclusive selection, groups, cards, and mixed state.' },
  { slug: 'switch', title: 'Switch', description: 'Immediate binary settings, sizes, settings cards, and async state.' },
  { slug: 'card', title: 'Card', description: 'Semantic content grouping, density, depth, media, and interactive variants.' },
  { slug: 'divider', title: 'Divider', description: 'Semantic and decorative separation, emphasis, spacing, labels, and orientation.' },
  { slug: 'avatar', title: 'Avatar', description: 'Images, initials, fallbacks, sizes, presence, groups, and interactive use.' },
  { slug: 'spinner', title: 'Spinner', description: 'Indeterminate progress, sizes, tones, status labels, and busy regions.' },
  { slug: 'skeleton', title: 'Skeleton', description: 'Layout-preserving text, identity, media, control, and card placeholders.' },
  { slug: 'alert', title: 'Alert', description: 'Persistent feedback with semantic tone, actions, dismissal, and clear announcement behavior.' },
  { slug: 'disclosure-accordion', title: 'Disclosure and Accordion', description: 'Native progressive disclosure with multiple-open and optional single-open behavior.' },
  { slug: 'tabs', title: 'Tabs', description: 'Related views with roving focus, two activation models, vertical layout, and overflow behavior.' },
  { slug: 'dialog', title: 'Dialog', description: 'Focused modal tasks with native containment, deliberate dismissal, and focus restoration.' },
  { slug: 'popover-menu', title: 'Popover and Dropdown Menu', description: 'Anchored context and actions with native light dismissal, roving focus, and typeahead.' },
  { slug: 'tooltip', title: 'Tooltip', description: 'Concise supporting labels with pointer, keyboard, adaptive placement, and Escape dismissal.' },
  { slug: 'toast', title: 'Toast', description: 'Temporary status messages with semantic priority, bounded queues, actions, and interaction-aware timing.' },
  { slug: 'header-navigation', title: 'Header and Navigation', description: 'Container-aligned product identity, primary destinations, actions, and resilient compact disclosure.' },
  { slug: 'breadcrumb-pagination', title: 'Breadcrumb and Pagination', description: 'Hierarchy and stable result-page movement with current, disabled, condensed, and responsive states.' },
  { slug: 'table', title: 'Table', description: 'Semantic structured data with sorting, selection, density, overflow, numeric, and empty states.' },
  { slug: 'product-states', title: 'Product States', description: 'Empty, no-result, loading, error, and success compositions with clear recovery and announcement guidance.', type: 'pattern' },
  { slug: 'search-filter', title: 'Search and Filter', description: 'Durable query forms, explicit criteria, active filters, result counts, responsive layout, and empty recovery.', type: 'pattern' },
  { slug: 'form-validation', title: 'Form Validation and Submission', description: 'Native constraints, error summary focus, inline recovery, pending protection, and announced outcomes.', type: 'pattern' },
  { slug: 'settings-account', title: 'Settings and Account', description: 'Identity, immediate preferences, sessions, responsive categories, and consequential account actions.', type: 'pattern' },
  { slug: 'destructive-confirmation', title: 'Destructive Confirmation', description: 'Risk-proportional confirmation with concrete consequences, typed verification, protected submission, and recovery guidance.', type: 'pattern' },
]);
